# Generated by Django 5.1.3 on 2025-02-12 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_balances_iso_currency_code_bankaccount_balances_currency_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=37, unique=True)),
                ('account_id', models.CharField(max_length=37)),
                ('account_owner', models.CharField(max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('counterparties', models.JSONField(null=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('currency_code', models.CharField(max_length=10, null=True)),
                ('logo_url', models.URLField(max_length=1000, null=True)),
                ('merchant_name', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('payment_channel', models.CharField(max_length=255, null=True)),
                ('pending', models.BooleanField(null=True)),
                ('personal_finance_category', models.JSONField(null=True)),
                ('personal_finance_category_icon_url', models.URLField(max_length=1000, null=True)),
                ('website', models.URLField(max_length=1000, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.bankaccount')),
            ],
        ),
    ]
