# Generated by Django 5.1.3 on 2025-02-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_company_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(unique=True)),
                ('institution_id', models.CharField()),
                ('institution_name', models.CharField()),
            ],
        ),
    ]
