# Generated by Django 5.1.3 on 2025-02-26 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_transaction_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=None, null=True)),
                ('end_date', models.DateTimeField(default=None, null=True)),
                ('active', models.BooleanField(default=True)),
                ('payment_period', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('Y', 'Yearly'), ('VAR', 'Variable')], default='Monthly', null=True)),
                ('payment_type', models.CharField(choices=[('F', 'Fixed'), ('V', 'Variable')], default='Variable', null=True)),
                ('last_payment_date', models.DateTimeField(default=None, null=True)),
                ('next_payment_date', models.DateTimeField(default=None, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.application')),
                ('subscription_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
