# Generated by Django 5.1.3 on 2025-02-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='manage_subscription_link',
            field=models.URLField(default=None, max_length=5000, null=True),
        ),
    ]
