# Generated by Django 5.1.3 on 2025-03-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='related_names',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='linkedbank',
            name='access_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
