# Generated by Django 5.1.3 on 2025-03-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_application_related_names_linkedbank_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedbank',
            name='cursor',
            field=models.CharField(default='', max_length=255),
        ),
    ]
