# Generated by Django 5.1.3 on 2025-03-27 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_linkedbank_cursor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription_manager',
            new_name='user',
        ),
    ]
