# Generated by Django 5.1.3 on 2025-04-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_subscription_manager_subscription_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='datetime',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
