# Generated by Django 5.1.3 on 2025-04-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_transaction_datetime_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_payment_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='next_payment_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
