# Generated by Django 5.1.3 on 2025-06-19 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.subscription'),
        ),
    ]
