# Generated by Django 5.1.3 on 2025-06-28 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_transaction_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.company'),
            preserve_default=False,
        ),
    ]
