---
name: Checks

on: [push]

jobs:
  test-and-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    # setting env allows to check out that env's specific variables..but can also use non-env variables/secrets
    environment: development
    steps:
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore base64 encoded git bash .env files
        run: |
          echo "${{ secrets.ENV }}" | base64 --decode > .env
          echo "${{ secrets.SUBSY_BACKEND_ENV }}" | base64 --decode > ./subsy_backend/.env
          echo "${{ secrets.SUBSY_FRONTEND_ENV }}" | base64 --decode > ./subsy_frontend/.env
      - name: Test
        run: docker compose -f ./docker-compose.yml run --rm backend sh -c "python manage.py wait_for_db && python manage.py test"
        # # prev backend level docker compose
        # run: docker compose -f ./subsy_backend/docker-compose.yml run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      #   # removing Lint for now since many errors
      # - name: Lint
      #   run: docker compose -f ./docker-compose.yml run --rm backend sh -c "flake8"
      #   # run: docker compose -f ./subsy_backend/docker-compose.yml run --rm app sh -c "flake8"
